language: ruby
rvm: 2.7.1
cache: bundler
bundler_args: --retry=6
services:
  - postgresql
addons:
  postgresql: 9.6
before_script:
  - psql -c 'create database openstax_salesforce_api_test;' -U postgres
script:
  - bundle exec rspec