development:
  # Salesforce settings
  salesforce:
    login_domain: <%= ENV['SALESFORCE_LOGIN_DOMAIN'] || 'test.salesforce.com' %>
    username: <%= ENV['SALESFORCE_USERNAME'] %>
    password: <%= ENV['SALESFORCE_PASSWORD'] %>
    security_token: <%= ENV['SALESFORCE_SECURITY_TOKEN'] %>
    consumer_key: <%= ENV['SALESFORCE_CONSUMER_KEY'] %>
    consumer_secret: <%= ENV['SALESFORCE_CONSUMER_SECRET'] %>

  accounts:
    sso:
      signature_public_key: "<%= ENV['SSO_SIGNATURE_PUBLIC_KEY'] || '-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDjvO/E8lO+ZJ7JMglbJyiF5/Ae\nIIS2NKbIAMLBMPVBQY7mSqo6j/yxdVNKZCzYAMDWc/VvEfXQQJ2ipIUuDvO+SOwz\nMewQ70hC71hC4s3dmOSLnixDJlnsVpcnKPEFXloObk/fcpK2Vw27e+yY+kIFmV2X\nzrvTnmm9UJERp6tVTQIDAQAB\n-----END PUBLIC KEY-----\n' %>"
      encryption_private_key: "<%= ENV['SSO_ENCRYPTION_PRIVATE_KEY'] || 'c6d9b8683fddce8f2a39ac0565cf18ee' %>"
      cookie_name: <%= ENV['SSO_COOKIE_NAME'] || 'oxa' %>
      encryption_algorithm: <%= ENV['SSO_ENCRYPTION_ALGORITHM'] || 'dir' %>
      encryption_method: <%= ENV['SSO_ENCRYPTION_METHOD'] || 'A256GCM' %>
      signature_algorithm: <%= ENV['SSO_SIGNATURE_ALGORITHM'] || 'RS256' %>

  pardot:
    email: <%= ENV['PARDOT_EMAIL'] %>
    password: <%= ENV['PARDOT_PASSWORD'] %>
    user_key: <%= ENV['PARDOT_USER_KEY'] %>

test:
  # Salesforce settings
  salesforce:
    login_domain: <%= ENV['SALESFORCE_LOGIN_DOMAIN'] || 'test.salesforce.com' %>
    username: <%= ENV['SALESFORCE_USERNAME'] || 'salesforce_username' %>
    password: <%= ENV['SALESFORCE_PASSWORD'] || 'salesforce_password' %>
    security_token: <%= ENV['SALESFORCE_SECURITY_TOKEN'] || 'salesforce_security_token' %>
    consumer_key: <%= ENV['SALESFORCE_CONSUMER_KEY'] || 'salesforce_consumer_key' %>
    consumer_secret: <%= ENV['SALESFORCE_CONSUMER_SECRET'] || 'salesforce_consumer_secret' %>

  accounts:
    #these are not really secret and are from the Accounts secrets.example file
    sso:
      signature_public_key: "<%= ENV['SSO_SIGNATURE_PUBLIC_KEY'] || '-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDjvO/E8lO+ZJ7JMglbJyiF5/Ae\nIIS2NKbIAMLBMPVBQY7mSqo6j/yxdVNKZCzYAMDWc/VvEfXQQJ2ipIUuDvO+SOwz\nMewQ70hC71hC4s3dmOSLnixDJlnsVpcnKPEFXloObk/fcpK2Vw27e+yY+kIFmV2X\nzrvTnmm9UJERp6tVTQIDAQAB\n-----END PUBLIC KEY-----\n' %>"
      encryption_private_key: "<%= ENV['SSO_ENCRYPTION_PRIVATE_KEY'] || 'c6d9b8683fddce8f2a39ac0565cf18ee' %>"
      cookie_name: <%= ENV['SSO_COOKIE_NAME'] || 'oxa' %>
      encryption_algorithm: <%= ENV['SSO_ENCRYPTION_ALGORITHM'] || 'dir' %>
      encryption_method: <%= ENV['SSO_ENCRYPTION_METHOD'] || 'A256GCM' %>
      signature_algorithm: <%= ENV['SSO_SIGNATURE_ALGORITHM'] || 'RS256' %>
